sudo: required

language: python
python:
    - '3.7'

before_install:
    - sudo apt-get update
    - sudo apt-get -y install python3-pip libdbus-glib-1-dev libcairo2-dev libglib2.0-dev libgirepository1.0-dev gir1.2-gtk-3.0 vlc libvlc-dev
    - sudo pip3 install --upgrade pip
    - pip3 install pygobject

install:
    - pip3 install '.[mpv, dev]'

# Lint with PEP8 and run tests
script: 
    - flake8 . --ignore='F821,W503'
    - python -m unittest

notifications:
    email: false
