sudo: required

language: python
python:
    - '3.6'
    - '3.7'

# Install PEP8 linter and dependencies
before_install:
    - sudo apt-get update
    - sudo apt-get -y install python3-pip
    - sudo pip3 install --upgrade pip
    - pip3 install flake8
    - sudo apt-get -y install libdbus-glib-1-dev libcairo2-dev libglib2.0-dev libgirepository1.0-dev gir1.2-gtk-3.0 vlc libvlc-dev
    - pip3 install pygobject
install:
    - python setup.py install

# Lint with PEP8 (skipping spotipy) and do tests
script: 
    - flake8 . --exclude 'spotipy' --ignore='F821,W503'
    - python -m unittest

notifications:
    email: false
