sudo: required

language: python
python:
    - '3.7'

services:
  - xvfb

before_install:
    - sudo add-apt-repository -y ppa:mc3man/mpv-tests
    - sudo apt-get update
    - sudo apt-get -y install python3-pip libdbus-glib-1-dev libcairo2-dev 
         libglib2.0-dev libgirepository1.0-dev gir1.2-gtk-3.0 vlc libvlc-dev
         mpv libmpv-dev

install:
    - pip3 install .[mpv,dev]
    - pip3 install swspotify

# Lint with PEP8 and run tests
script: 
    - flake8 . --ignore='F821,W503,E731'
    - python -m unittest

notifications:
    email: false
